scala_library(name = 'finch',
  dependencies = [
     '3rdparty/jvm/org/spire:cats-core',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless-snapshot',
     '3rdparty/jvm/com/twitter:finagle-http',
     '3rdparty/jvm/org/typelevel:export-hook',
  ],
    sources = globs('*.scala','internal/*.scala'),
)
