package io.finch.petstore

import argonaut.Argonaut._
import argonaut.CodecJson

/**
 * Represents a Category object for pets. This is the type of animal a pet is.
 * @param id The unique, autogenerated ID of this Category.
 * @param name The name of this Category.
 */
case class Category(id: Option[Long], name: String)

/**
 * Provides encoding and decoding methods for Category objects.
 */
object Category {
  /**
   * Creates the codec for Category objects.
   */
  implicit val categoryCodec: CodecJson[Category] =
    casecodec2(Category.apply, Category.unapply)("id", "name")
}
