scala_library(name = 'incompletes',
  dependencies = [
   'projects/finch/src/scala/finch/core/src/main/scala/io/finch',
   '3rdparty/jvm/com/twitter:twitter-server',
   '3rdparty/jvm/com/twitter:finagle-http',
  ],
  sources = globs('*.scala','internal/*.scala'),
)
 
