name: Scala CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['adopt@1.11']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: set up sbt and java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests
        shell: bash
        env:
          ENCRYPTION_PASSWORD: ${{secrets.ENCRYPTION_PASSWORD}}
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
        run: ./build/build.sh
